### ISSUE TITLE
jdbc `initialize-schema` creates table with default name, not the one from `table-name` property

### ISSUE THREAD

**Issue by jm-ck** [spring-projects/spring-session#1230]
Spring Session JDBC when requested to `always` initialize schema, creates tables named with default name (`SPRING_SESSION`) even when `table-name` param is overriding this name. Later at runtime, tables defined in `table-name` are missing, because not created by Spring Session.

Full config of SpringSession: 
```
spring.session:
    store-type: jdbc
    jdbc:
      table-name: SPRING_SESSION_V2
      initialize-schema: always
```
 
version: 2.1.0.RELEASE
