### ISSUE TITLE
App crush when Redis instance restart

### ISSUE THREAD

**Issue by zjh-coder** [spring-projects/spring-session#2745]
**Describe the bug**
I'm using spring-session and a redis cluster in an app, and when I restart the redis instances in the cluster, it causes the app to shut down

**To Reproduce**
dependency in pom:
```
<dependency>
    <groupId>org.springframework.session</groupId>
    <artifactId>spring-session-data-redis</artifactId>
    <version>3.1.2</version>
</dependency>
```
Configuration in application.yml:

```
spring:
  data:
    redis:
      timeout: 20000ms
      cluster:
        nodes: host:6380, host:6381, host:6382
      password: dasdkhasjkd
```
**Expected behavior**
spring-session can handle node failures in redis clusters properly

**Sample**
not yet
